/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class encryption_JniKeyEncrypt */

#ifndef _Included_encryption_JniKeyEncrypt
#define _Included_encryption_JniKeyEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     encryption_JniKeyEncrypt
 * Method:    generateKeyEncryptKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_encryption_JniKeyEncrypt_generateKeyEncryptKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     encryption_JniKeyEncrypt
 * Method:    generateEncryptKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_encryption_JniKeyEncrypt_generateEncryptKey
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     encryption_JniKeyEncrypt
 * Method:    regenerateEncryptKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_encryption_JniKeyEncrypt_regenerateEncryptKey
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
